In [29]:
#Importing libraries
import pandas as pd
import numpy as np

In [30]:
#Read the movie content
i_cols = ['movie id', 'movie title' ,'release date','video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
items = pd.read_csv('ml-100k/u.item', sep='|', names=i_cols, encoding='latin-1')

In [31]:
items

,movie id,movie title,release date,video release date,IMDb URL,unknown,Action,Adventure,Animation,Children's,...,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Toy%20Story%2...,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?GoldenEye%20(...,0,1,1,0,0,...,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Four%20Rooms%...,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Get%20Shorty%...,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),01-Jan-1995,NaN,http://us.imdb.com/M/title-exact?Copycat%20(1995),0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?Mat%27+i+syn+...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),06-Feb-1998,NaN,http://us.imdb.com/M/title-exact?B%2E+Monkey+(...,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),01-Jan-1998,NaN,http://us.imdb.com/Title?Sliding+Doors+(1998),0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),01-Jan-1994,NaN,http://us.imdb.com/M/title-exact?You%20So%20Cr...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),08-Mar-1996,NaN,http://us.imdb.com/M/title-exact?Schrei%20aus%...,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [32]:
movie_content = items[['movie id','movie title','Action', 'Adventure',
    'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
    'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']]
movie_content

,movie id,movie title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,GoldenEye (1995),1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
2,3,Four Rooms (1995),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,Get Shorty (1995),1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Copycat (1995),0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1677,1678,Mat' i syn (1997),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1678,1679,B. Monkey (1998),0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0
1679,1680,Sliding Doors (1998),0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0
1680,1681,You So Crazy (1994),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1681,1682,Scream of Stone (Schrei aus Stein) (1991),0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [33]:
#create rating table from data
r_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=r_cols, encoding='latin-1')

In [34]:
ratings

       user_id  movie_id  rating  unix_timestamp
0          196       242       3       881250949
1          186       302       3       891717742
2           22       377       1       878887116
3          244        51       2       880606923
4          166       346       1       886397596
...        ...       ...     ...             ...
99995      880       476       3       880175444
99996      716       204       5       879795543
99997      276      1090       1       874795795
99998       13       225       2       882399156
99999       12       203       3       879959583

[100000 rows x 4 columns]

In [35]:
# List of genre columns
genres = ['Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime','Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [36]:
# Let's cerate empty Dictionary to hold DataFrames for each genre
genre_dfs = {}

In [37]:
for i in genres:
    genre_dfs[i] = movie_content[movie_content[i] == 1][['movie id', 'movie title']]

In [38]:
len(genre_dfs)

18

In [39]:
#checking
genre_dfs[genres[0]]

      movie id                    movie title
1            2               GoldenEye (1995)
3            4              Get Shorty (1995)
16          17     From Dusk Till Dawn (1996)
20          21  Muppet Treasure Island (1996)
21          22              Braveheart (1995)
...        ...                            ...
1614      1615      Warriors of Virtue (1997)
1617      1618        King of New York (1990)
1645      1646           Men With Guns (1997)
1656      1657                  Target (1995)
1672      1673                  Mirage (1995)

[251 rows x 2 columns]

In [40]:
#Cross checking to access the tuples.
genre_dfs.items()

dict_items([('Action',       movie id                    movie title
1            2               GoldenEye (1995)
3            4              Get Shorty (1995)
16          17     From Dusk Till Dawn (1996)
20          21  Muppet Treasure Island (1996)
21          22              Braveheart (1995)
...        ...                            ...
1614      1615      Warriors of Virtue (1997)
1617      1618        King of New York (1990)
1645      1646           Men With Guns (1997)
1656      1657                  Target (1995)
1672      1673                  Mirage (1995)

[251 rows x 2 columns]), ('Adventure',       movie id                                        movie title
1            2                                   GoldenEye (1995)
20          21                      Muppet Treasure Island (1996)
23          24                         Rumble in the Bronx (1995)
28          29                              Batman Forever (1995)
34          35            Free Willy 2: The Adventure Home (1995)
...        ...                                                ...
1530      1531  Far From Home: The Adventures of Yellow Dog (1...
1539      1540                Amazing Panda Adventure, The (1995)
1554      1555         Secret Adventures of Tom Thumb, The (1993)
1607      1608                                       Buddy (1997)
1614      1615                          Warriors of Virtue (1997)

[135 rows x 2 columns]), ('Animation',       movie id                                        movie title
0            1                                   Toy Story (1995)
70          71                              Lion King, The (1994)
94          95                                     Aladdin (1992)
98          99             Snow White and the Seven Dwarfs (1937)
100        101                                 Heavy Metal (1981)
101        102                             Aristocats, The (1970)
102        103                     All Dogs Go to Heaven 2 (1996)
113        114  Wallace & Gromit: The Best of Aardman Animatio...
168        169                         Wrong Trousers, The (1993)
188        189                            Grand Day Out, A (1992)
205        206                                       Akira (1988)
239        240             Beavis and Butt-head Do America (1996)
403        404                                   Pinocchio (1940)
407        408                              Close Shave, A (1995)
417        418                                  Cinderella (1950)
419        420                         Alice in Wonderland (1951)
421        422             Aladdin and the King of Thieves (1996)
425        426                Transformers: The Movie, The (1986)
431        432                                    Fantasia (1940)
472        473                   James and the Giant Peach (1996)
500        501                                       Dumbo (1941)
537        538                                   Anastasia (1997)
541        542                                  Pocahontas (1995)
587        588                        Beauty and the Beast (1991)
595        596                Hunchback of Notre Dame, The (1996)
623        624                       Three Caballeros, The (1945)
624        625                     Sword in the Stone, The (1963)
819        820                                   Space Jam (1996)
945        946                      Fox and the Hound, The (1981)
968        969        Winnie the Pooh and the Blustery Day (1968)
988        989                            Cats Don't Dance (1997)
992        993                                    Hercules (1997)
1065      1066                                       Balto (1995)
1075      1076                             Pagemaster, The (1994)
1077      1078                            Oliver & Company (1988)
1090      1091                               Pete's Dragon (1977)
1218      1219                              Goofy Movie, A (1995)
1239      1240         Ghost in the Shell (Kokaku kidotai) (1995)
1366      1367                                       Faust (1994)
1408      1409                          Swan Princess, The (1994)
1411      1412  Land Before Time III: The Time of the Great Gi...
1469      1470                            Gumby: The Movie (1995)), ("Children's",       movie id                                        movie title
0            1                                   Toy Story (1995)
7            8                                        Babe (1995)
34          35            Free Willy 2: The Adventure Home (1995)
62          63                           Santa Clause, The (1994)
70          71                              Lion King, The (1994)
...        ...                                                ...
1530      1531  Far From Home: The Adventures of Yellow Dog (1...
1539      1540                Amazing Panda Adventure, The (1995)
1554      1555         Secret Adventures of Tom Thumb, The (1993)
1607      1608                                       Buddy (1997)
1614      1615                          Warriors of Virtue (1997)

[122 rows x 2 columns]), ('Comedy',       movie id                         movie title
0            1                    Toy Story (1995)
3            4                   Get Shorty (1995)
7            8                         Babe (1995)
12          13             Mighty Aphrodite (1995)
15          16  French Twist (Gazon maudit) (1995)
...        ...                                 ...
1658      1659     Getting Away With Murder (1996)
1663      1664      8 Heads in a Duffel Bag (1997)
1667      1668           Wedding Bell Blues (1996)
1669      1670                      Tainted (1998)
1680      1681                 You So Crazy (1994)

[505 rows x 2 columns]), ('Crime',       movie id                         movie title
4            5                      Copycat (1995)
10          11                Seven (Se7en) (1995)
11          12          Usual Suspects, The (1995)
16          17          From Dusk Till Dawn (1996)
23          24          Rumble in the Bronx (1995)
...        ...                                 ...
1609      1610  Truth or Consequences, N.M. (1997)
1617      1618             King of New York (1990)
1637      1638                  Normal Life (1996)
1646      1647                      Hana-bi (1997)
1668      1669            MURDER and murder (1996)

[109 rows x 2 columns]), ('Documentary',       movie id                                        movie title
31          32                                       Crumb (1994)
47          48                                 Hoop Dreams (1994)
74          75  Brother Minister: The Assassination of Malcolm...
114        115    Haunted World of Edward D. Wood Jr., The (1995)
118        119             Maya Lin: A Strong Clear Vision (1994)
319        320  Paradise Lost: The Child Murders at Robin Hood...
359        360                                  Wonderland (1997)
633        634           Microcosmos: Le peuple de l'herbe (1996)
643        644                         Thin Blue Line, The (1988)
644        645                            Paris Is Burning (1990)
676        677                        Fire on the Mountain (1996)
700        701  Wonderful, Horrible Life of Leni Riefenstahl, ...
756        757                      Across the Sea of Time (1995)
765        766                             Man of the Year (1995)
810        811    Thirty-Two Short Films About Glenn Gould (1993)
812        813                       Celluloid Closet, The (1995)
813        814                      Great Day in Harlem, A (1994)
846        847                         Looking for Richard (1996)
849        850                        Perfect Candidate, A (1996)
856        857                           Paris Was a Woman (1995)
883        884                           Year of the Horse (1997)
953        954                                    Unzipped (1995)
972        973                               Grateful Dead (1995)
1021      1022                Fast, Cheap & Out of Control (1997)
1064      1065                               Koyaanisqatsi (1983)
1083      1084                       Anne Frank Remembered (1995)
1127      1128              Heidi Fleiss: Hollywood Madam (1995)
1129      1130                              Jupiter's Wife (1994)
1140      1141                               War Room, The (1993)
1141      1142                          When We Were Kings (1996)
1183      1184                       Endless Summer 2, The (1994)
1200      1201         Marlene Dietrich: Shadow and Light (1996)
1231      1232                      Madonna: Truth or Dare (1991)
1293      1294                   Ayn Rand: A Sense of Life (1997)
1306      1307      Carmen Miranda: Bananas Is My Business (1994)
1317      1318                                     Catwalk (1995)
1330      1331  Last Klezmer: Leopold Kozlowski, His Life and ...
1362      1363                            Leopard Son, The (1996)
1365      1366          JLG/JLG - autoportrait de décembre (1994)
1377      1378                              Rhyme & Reason (1997)
1481      1482                 Gate of Heavenly Peace, The (1995)
1496      1497               Line King: Al Hirschfeld, The (1996)
1546      1547                                   Show, The (1995)
1560      1561         Tigrero: A Film That Was Never Made (1994)
1561      1562       Eye of Vichy, The (Oeil de Vichy, L') (1993)
1584      1585                              American Dream (1990)
1593      1594                                     Everest (1998)
1628      1629                                   Nico Icon (1995)
1640      1641                                    Dadetown (1995)
1648      1649                                Big One, The (1997)), ('Drama',       movie id                                        movie title
3            4                                  Get Shorty (1995)
4            5                                     Copycat (1995)
5            6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...
6            7                              Twelve Monkeys (1995)
7            8                                        Babe (1995)
...        ...                                                ...
1675      1676                            War at Home, The (1996)
1676      1677                               Sweet Nothing (1995)
1677      1678                                  Mat' i syn (1997)
1679      1680                               Sliding Doors (1998)
1681      1682          Scream of Stone (Schrei aus Stein) (1991)

[725 rows x 2 columns]), ('Fantasy',       movie id                           movie title
71          72                      Mask, The (1994)
140        141   20,000 Leagues Under the Sea (1954)
307        308        FairyTale: A True Story (1997)
410        411           Nutty Professor, The (1996)
422        423     E.T. the Extra-Terrestrial (1982)
471        472                    Dragonheart (1996)
547        548     NeverEnding Story III, The (1994)
557        558             Heavenly Creatures (1994)
559        560  Kid in King Arthur's Court, A (1995)
754        755                        Jumanji (1995)
819        820                      Space Jam (1996)
831        832                          Bogus (1996)
891        892                        Flubber (1997)
950        951    Indian in the Cupboard, The (1995)
1035      1036                 Drop Dead Fred (1991)
1075      1076                Pagemaster, The (1994)
1132      1133       Escape to Witch Mountain (1975)
1291      1292                 Simple Wish, A (1997)
1292      1293                       Star Kid (1997)
1335      1336                         Kazaam (1996)
1575      1576        Hungarian Fairy Tale, A (1987)
1614      1615             Warriors of Virtue (1997)), ('Film-Noir',       movie id                       movie title
88          89               Blade Runner (1982)
298        299                    Hoodlum (1997)
301        302          L.A. Confidential (1997)
483        484        Maltese Falcon, The (1941)
487        488               Sunset Blvd. (1950)
488        489                  Notorious (1946)
524        525             Big Sleep, The (1946)
610        611                      Laura (1944)
641        642              Grifters, The (1990)
652        653              Touch of Evil (1958)
653        654                  Chinatown (1974)
655        656                          M (1931)
656        657  Manchurian Candidate, The (1962)
672        673                  Cape Fear (1962)
690        691                  Dark City (1998)
769        770      Devil in a Blue Dress (1995)
822        823           Mulholland Falls (1996)
847        848           Murder, My Sweet (1944)
1063      1064                  Crossfire (1947)
1312      1313                   Palmetto (1998)
1421      1422                     Suture (1993)
1475      1476                   Raw Deal (1948)
1581      1582                      T-Men (1947)
1603      1604         He Walked by Night (1948)), ('Horror',       movie id                                        movie title
16          17                         From Dusk Till Dawn (1996)
83          84     Robert A. Heinlein's The Puppet Masters (1994)
100        101                                 Heavy Metal (1981)
122        123                            Frighteners, The (1996)
182        183                                       Alien (1979)
...        ...                                                ...
1370      1371                                Machine, The (1994)
1476      1477                                  Nightwatch (1997)
1519      1520                                   Fear, The (1995)
1572      1573  Spirits of the Dead (Tre passi nel delirio) (1...
1624      1625                                  Nightwatch (1997)

[92 rows x 2 columns]), ('Musical',       movie id                                        movie title
20          21                      Muppet Treasure Island (1996)
70          71                              Lion King, The (1994)
90          91             Nightmare Before Christmas, The (1993)
94          95                                     Aladdin (1992)
98          99             Snow White and the Seven Dwarfs (1937)
102        103                     All Dogs Go to Heaven 2 (1996)
131        132                           Wizard of Oz, The (1939)
141        142                    Bedknobs and Broomsticks (1971)
142        143                         Sound of Music, The (1965)
154        155                               Dirty Dancing (1987)
185        186                         Blues Brothers, The (1980)
208        209                          This Is Spinal Tap (1984)
213        214                       Pink Floyd - The Wall (1982)
288        289                                       Evita (1996)
318        319                    Everyone Says I Love You (1996)
351        352                                 Spice World (1997)
361        362                         Blues Brothers 2000 (1998)
417        418                                  Cinderella (1950)
418        419                                Mary Poppins (1964)
419        420                         Alice in Wonderland (1951)
431        432                                    Fantasia (1940)
450        451                                      Grease (1978)
472        473                   James and the Giant Peach (1996)
484        485                                My Fair Lady (1964)
500        501                                       Dumbo (1941)
537        538                                   Anastasia (1997)
541        542                                  Pocahontas (1995)
542        543                             Misérables, Les (1995)
556        557                      Farinelli: il castrato (1994)
587        588                        Beauty and the Beast (1991)
595        596                Hunchback of Notre Dame, The (1996)
601        602                       American in Paris, An (1951)
604        605                        Meet Me in St. Louis (1944)
609        610                                        Gigi (1958)
623        624                       Three Caballeros, The (1945)
628        629                             Victor/Victoria (1982)
629        630                             Great Race, The (1965)
704        705                         Singin' in the Rain (1952)
834        835                           Gay Divorcee, The (1934)
964        965                                  Funny Face (1957)
967        968                      Inspector General, The (1949)
988        989                            Cats Don't Dance (1997)
992        993                                    Hercules (1997)
1036      1037                                    Grease 2 (1982)
1078      1079                             Joe's Apartment (1996)
1090      1091                               Pete's Dragon (1977)
1109      1110                                   Tank Girl (1995)
1120      1121  Umbrellas of Cherbourg, The (Parapluies de Che...
1134      1135                                  Doors, The (1991)
1152      1153                                    Backbeat (1993)
1202      1203                                     Top Hat (1935)
1277      1278                                      Selena (1997)
1285      1286                             Shall We Dance? (1937)
1297      1298                             Band Wagon, The (1953)
1457      1458                       Damsel in Distress, A (1937)
1458      1459                            Madame Butterfly (1995)), ('Mystery',       movie id                    movie title
123        124               Lone Star (1996)
134        135   2001: A Space Odyssey (1968)
158        159          Basic Instinct (1992)
190        191                 Amadeus (1984)
259        260           Event Horizon (1997)
...        ...                            ...
1443      1444          That Darn Cat! (1965)
1451      1452       Lady of Burlesque (1943)
1552      1553         Underneath, The (1995)
1580      1581  Woman in Question, The (1950)
1668      1669       MURDER and murder (1996)

[61 rows x 2 columns]), ('Romance',       movie id                         movie title
13          14                  Postino, Il (1994)
15          16  French Twist (Gazon maudit) (1995)
19          20           Angels and Insects (1995)
32          33                    Desperado (1995)
35          36                     Mad Love (1995)
...        ...                                 ...
1654      1655                   Favor, The (1994)
1655      1656                  Little City (1998)
1661      1662                  Rough Magic (1995)
1678      1679                    B. Monkey (1998)
1679      1680                Sliding Doors (1998)

[247 rows x 2 columns]), ('Sci-Fi',       movie id                            movie title
6            7                  Twelve Monkeys (1995)
37          38                        Net, The (1995)
38          39                    Strange Days (1995)
49          50                       Star Wars (1977)
61          62                        Stargate (1994)
...        ...                                    ...
1410      1411                      Barbarella (1968)
1415      1416                       No Escape (1994)
1418      1419    Highlander III: The Sorcerer (1994)
1471      1472  Visitors, The (Visiteurs, Les) (1993)
1595      1596               Nemesis 2: Nebula (1995)

[101 rows x 2 columns]), ('Thriller',       movie id                   movie title
1            2              GoldenEye (1995)
2            3             Four Rooms (1995)
4            5                Copycat (1995)
10          11          Seven (Se7en) (1995)
11          12    Usual Suspects, The (1995)
...        ...                           ...

In [41]:
#create empty dictionary for to store df for top5 movies in each genre
top5_by_genre = {}

for genre, df in genre_dfs.items():     
# genre is key & df is value in dictionary
# .items() returns all pairs from the dictionary as tuples:

    # first we will bring ratings for movies by merging/vlook up in excel
    merged = pd.merge(df, ratings, left_on='movie id', right_on='movie_id')
    
    # Group ratings by movie id and title. Each movie has different ratings by diff users in groups now.
    grouped = merged.groupby(['movie id', 'movie title'])['rating']

    #Find mean rating for each movie grouped. we can't just go with mzx rating if it is an outlier (e.g) only one raing in top.
    avg_rating_per_movie = grouped.mean()

    #Convert groupings back into a DataFrame
    avg_ratings = pd.DataFrame(avg_rating_per_movie)

    #Sort movies by average rating (in decending order)
    avg_ratings_sorted = avg_ratings.sort_values(by='rating', ascending=False)

    # Select top 5 movies for this genre (it loops through for loop for each genre & df)
    top5 = avg_ratings_sorted.head(5)
    
    #storing in dictionary..
    top5_by_genre[genre] = top5

In [43]:
top5_by_genre

{'Action':                                             rating
 movie id movie title
 50       Star Wars (1977)                 4.358491
 127      Godfather, The (1972)            4.283293
 174      Raiders of the Lost Ark (1981)   4.252381
 313      Titanic (1997)                   4.245714
 172      Empire Strikes Back, The (1980)  4.204360,
 'Adventure':                                             rating
 movie id movie title
 1293     Star Kid (1997)                  5.000000
 50       Star Wars (1977)                 4.358491
 174      Raiders of the Lost Ark (1981)   4.252381
 511      Lawrence of Arabia (1962)        4.231214
 172      Empire Strikes Back, The (1980)  4.204360,
 'Animation':                                                                rating
 movie id movie title
 408      Close Shave, A (1995)                               4.491071
 169      Wrong Trousers, The (1993)                          4.466102
 114      Wallace & Gromit: The Best of Aardman Animation...  4.447761
 1367     Faust (1994)                                        4.200000
 189      Grand Day Out, A (1992)                             4.106061,
 "Children's":                                      rating
 movie id movie title
 1293     Star Kid (1997)           5.000000
 132      Wizard of Oz, The (1939)  4.077236
 8        Babe (1995)               3.995434
 500      Fly Away Home (1996)      3.903226
 1        Toy Story (1995)          3.878319,
 'Comedy':                                        rating
 movie id movie title
 1500     Santa with Muscles (1996)   5.000000
 408      Close Shave, A (1995)       4.491071
 169      Wrong Trousers, The (1993)  4.466102
 480      North by Northwest (1959)   4.284916
 251      Shall We Dance? (1996)      4.260870,
 'Crime':                                             rating
 movie id movie title
 1122     They Made Me a Criminal (1939)   5.000000
 12       Usual Suspects, The (1995)       4.385768
 1191     Letter From Death Row, A (1998)  4.333333
 127      Godfather, The (1972)            4.283293
 1064     Crossfire (1947)                 4.250000,
 'Documentary':                                                        rating
 movie id movie title
 814      Great Day in Harlem, A (1994)               5.000000
 1201     Marlene Dietrich: Shadow and Light (1996)   5.000000
 1594     Everest (1998)                              4.500000
 119      Maya Lin: A Strong Clear Vision (1994)      4.500000
 48       Hoop Dreams (1994)                          4.094017,
 'Drama':                                                rating
 movie id movie title
 1122     They Made Me a Criminal (1939)           5.0
 1536     Aiqing wansui (1994)                     5.0
 1467     Saint of Fort Washington, The (1993)     5.0
 1599     Someone Else's America (1995)            5.0
 1189     Prefontaine (1997)                       5.0,
 'Fantasy':                                                 rating
 movie id movie title
 1293     Star Kid (1997)                      5.000000
 423      E.T. the Extra-Terrestrial (1982)    3.833333
 558      Heavenly Creatures (1994)            3.671429
 141      20,000 Leagues Under the Sea (1954)  3.500000
 755      Jumanji (1995)                       3.312500,
 'Film-Noir':                                              rating
 movie id movie title
 657      Manchurian Candidate, The (1962)  4.259542
 1064     Crossfire (1947)                  4.250000
 484      Maltese Falcon, The (1941)        4.210145
 488      Sunset Blvd. (1950)               4.200000
 302      L.A. Confidential (1997)          4.161616,
 'Horror':                                       rating
 movie id movie title
 185      Psycho (1960)              4.100418
 183      Alien (1979)               4.034364
 1625     Nightwatch (1997)          4.000000
 208      Young Frankenstein (1974)  3.945000
 853      Braindead (1992)           3.857143,
 'Musical':                                          rating
 movie id movie title
 132      Wizard of Oz, The (1939)      4.077236
 1203     Top Hat (1935)                4.047619
 1458     Damsel in Distress, A (1937)  4.000000
 705      Singin' in the Rain (1952)    3.992701
 209      This Is Spinal Tap (1984)     3.905759,
 'Mystery':                                        rating
 movie id movie title
 603      Rear Window (1954)          4.387560
 513      Third Man, The (1949)       4.333333
 479      Vertigo (1958)              4.251397
 484      Maltese Falcon, The (1941)  4.210145
 191      Amadeus (1984)              4.163043,
 'Romance':                                             rating
 movie id movie title
 483      Casablanca (1942)                4.456790
 50       Star Wars (1977)                 4.358491
 313      Titanic (1997)                   4.245714
 172      Empire Strikes Back, The (1980)  4.204360
 966      Affair to Remember, An (1957)    4.192308,
 'Sci-Fi':                                                                rating
 movie id movie title
 1293     Star Kid (1997)                                     5.000000
 50       Star Wars (1977)                                    4.358491
 474      Dr. Strangelove or: How I Learned to Stop Worry...  4.252577
 172      Empire Strikes Back, The (1980)                     4.204360
 89       Blade Runner (1982)                                 4.138182,
 'Thriller':                                                     rating
 movie id movie title
 408      Close Shave, A (1995)                    4.491071
 603      Rear Window (1954)                       4.387560
 12       Usual Suspects, The (1995)               4.385768
 513      Third Man, The (1949)                    4.333333
 963      Some Folks Call It a Sling Blade (1993)  4.292683,
 'War':                                                                rating
 movie id movie title
 318      Schindler's List (1993)                             4.466443
 483      Casablanca (1942)                                   4.456790
 50       Star Wars (1977)                                    4.358491
 474      Dr. Strangelove or: How I Learned to Stop Worry...  4.252577
 511      Lawrence of Arabia (1962)                           4.231214,
 'Western':                                                       rating
 movie id movie title
 661      High Noon (1952)                           4.102273
 589      Wild Bunch, The (1969)                     4.023256
 435      Butch Cassidy and the Sundance Kid (1969)  3.949074
 510      Magnificent Seven, The (1954)              3.942149
 646      Once Upon a Time in the West (1969)        3.868421}

In [51]:
len(top5_by_genre)

18

In [52]:
# let's print clearly as df
for genre, df in top5_by_genre.items():
    print(f"\nTop 5 movies in {genre} genre are:\n") #\n is for next line printing
    display(df)

Top 5 movies in Action genre are:

                                            rating
movie id movie title
50       Star Wars (1977)                 4.358491
127      Godfather, The (1972)            4.283293
174      Raiders of the Lost Ark (1981)   4.252381
313      Titanic (1997)                   4.245714
172      Empire Strikes Back, The (1980)  4.204360

Top 5 movies in Adventure genre are:

                                            rating
movie id movie title
1293     Star Kid (1997)                  5.000000
50       Star Wars (1977)                 4.358491
174      Raiders of the Lost Ark (1981)   4.252381
511      Lawrence of Arabia (1962)        4.231214
172      Empire Strikes Back, The (1980)  4.204360

Top 5 movies in Animation genre are:

                                                               rating
movie id movie title
408      Close Shave, A (1995)                               4.491071
169      Wrong Trousers, The (1993)                          4.466102
114      Wallace & Gromit: The Best of Aardman Animation...  4.447761
1367     Faust (1994)                                        4.200000
189      Grand Day Out, A (1992)                             4.106061

Top 5 movies in Children's genre are:

                                     rating
movie id movie title
1293     Star Kid (1997)           5.000000
132      Wizard of Oz, The (1939)  4.077236
8        Babe (1995)               3.995434
500      Fly Away Home (1996)      3.903226
1        Toy Story (1995)          3.878319

Top 5 movies in Comedy genre are:

                                       rating
movie id movie title
1500     Santa with Muscles (1996)   5.000000
408      Close Shave, A (1995)       4.491071
169      Wrong Trousers, The (1993)  4.466102
480      North by Northwest (1959)   4.284916
251      Shall We Dance? (1996)      4.260870

Top 5 movies in Crime genre are:

                                            rating
movie id movie title
1122     They Made Me a Criminal (1939)   5.000000
12       Usual Suspects, The (1995)       4.385768
1191     Letter From Death Row, A (1998)  4.333333
127      Godfather, The (1972)            4.283293
1064     Crossfire (1947)                 4.250000

Top 5 movies in Documentary genre are:

                                                       rating
movie id movie title
814      Great Day in Harlem, A (1994)               5.000000
1201     Marlene Dietrich: Shadow and Light (1996)   5.000000
1594     Everest (1998)                              4.500000
119      Maya Lin: A Strong Clear Vision (1994)      4.500000
48       Hoop Dreams (1994)                          4.094017

Top 5 movies in Drama genre are:

                                               rating
movie id movie title
1122     They Made Me a Criminal (1939)           5.0
1536     Aiqing wansui (1994)                     5.0
1467     Saint of Fort Washington, The (1993)     5.0
1599     Someone Else's America (1995)            5.0
1189     Prefontaine (1997)                       5.0

Top 5 movies in Fantasy genre are:

                                                rating
movie id movie title
1293     Star Kid (1997)                      5.000000
423      E.T. the Extra-Terrestrial (1982)    3.833333
558      Heavenly Creatures (1994)            3.671429
141      20,000 Leagues Under the Sea (1954)  3.500000
755      Jumanji (1995)                       3.312500

Top 5 movies in Film-Noir genre are:

                                             rating
movie id movie title
657      Manchurian Candidate, The (1962)  4.259542
1064     Crossfire (1947)                  4.250000
484      Maltese Falcon, The (1941)        4.210145
488      Sunset Blvd. (1950)               4.200000
302      L.A. Confidential (1997)          4.161616

Top 5 movies in Horror genre are:

                                      rating
movie id movie title
185      Psycho (1960)              4.100418
183      Alien (1979)               4.034364
1625     Nightwatch (1997)          4.000000
208      Young Frankenstein (1974)  3.945000
853      Braindead (1992)           3.857143

Top 5 movies in Musical genre are:

                                         rating
movie id movie title
132      Wizard of Oz, The (1939)      4.077236
1203     Top Hat (1935)                4.047619
1458     Damsel in Distress, A (1937)  4.000000
705      Singin' in the Rain (1952)    3.992701
209      This Is Spinal Tap (1984)     3.905759

Top 5 movies in Mystery genre are:

                                       rating
movie id movie title
603      Rear Window (1954)          4.387560
513      Third Man, The (1949)       4.333333
479      Vertigo (1958)              4.251397
484      Maltese Falcon, The (1941)  4.210145
191      Amadeus (1984)              4.163043

Top 5 movies in Romance genre are:

                                            rating
movie id movie title
483      Casablanca (1942)                4.456790
50       Star Wars (1977)                 4.358491
313      Titanic (1997)                   4.245714
172      Empire Strikes Back, The (1980)  4.204360
966      Affair to Remember, An (1957)    4.192308

Top 5 movies in Sci-Fi genre are:

                                                               rating
movie id movie title
1293     Star Kid (1997)                                     5.000000
50       Star Wars (1977)                                    4.358491
474      Dr. Strangelove or: How I Learned to Stop Worry...  4.252577
172      Empire Strikes Back, The (1980)                     4.204360
89       Blade Runner (1982)                                 4.138182

Top 5 movies in Thriller genre are:

                                                    rating
movie id movie title
408      Close Shave, A (1995)                    4.491071
603      Rear Window (1954)                       4.387560
12       Usual Suspects, The (1995)               4.385768
513      Third Man, The (1949)                    4.333333
963      Some Folks Call It a Sling Blade (1993)  4.292683

Top 5 movies in War genre are:

                                                               rating
movie id movie title
318      Schindler's List (1993)                             4.466443
483      Casablanca (1942)                                   4.456790
50       Star Wars (1977)                                    4.358491
474      Dr. Strangelove or: How I Learned to Stop Worry...  4.252577
511      Lawrence of Arabia (1962)                           4.231214

Top 5 movies in Western genre are:

                                                      rating
movie id movie title
661      High Noon (1952)                           4.102273
589      Wild Bunch, The (1969)                     4.023256
435      Butch Cassidy and the Sundance Kid (1969)  3.949074
510      Magnificent Seven, The (1954)              3.942149
646      Once Upon a Time in the West (1969)        3.868421